# Generated by Django 3.2.6 on 2021-08-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vorname', models.CharField(max_length=255)),
                ('Straße_Hausnummer', models.CharField(max_length=255)),
                ('postleitzahl', models.CharField(max_length=255)),
                ('stadt', models.CharField(max_length=255)),
                ('verein', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, default='images/no_image.png', null=True, upload_to='images/')),
            ],
        ),
    ]
