# Generated by Django 3.2.6 on 2021-08-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='Straße_Hausnummer',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='postleitzahl',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='stadt',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='foto',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='verein',
            new_name='post_code',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='vorname',
            new_name='society',
        ),
    ]
