# Generated by Django 3.2.6 on 2021-08-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20210807_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.FileField(blank=True, default='G:\\SCASE\\web_application\\mediaimages/no_image.png', null=True, upload_to='G:\\SCASE\\web_application\\mediaimages'),
        ),
    ]
