# Generated by Django 3.2.6 on 2021-08-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_alter_player_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='phone_number',
            field=models.FloatField(default=0),
        ),
    ]
