# Generated by Django 3.2.6 on 2021-08-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_alter_player_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='phone_number',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
