# Generated by Django 3.2.6 on 2021-08-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_alter_player_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(default=(2021, 8, 8, 15, 32, 15, 6, 220, 1)),
        ),
    ]
