# Generated by Django 3.2.6 on 2021-08-12 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_alter_player_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Player_Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.skills')),
            ],
        ),
    ]
