# Generated by Django 3.2.6 on 2021-08-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_player_skill_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_skill',
            name='feed_back',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
