# Generated by Django 3.2.6 on 2021-08-15 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_auto_20210815_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 8, 15, 14, 21, 24, 840600))),
                ('created_by', models.CharField(max_length=255)),
            ],
        ),
    ]
