# Generated by Django 3.2.6 on 2021-08-15 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0017_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='plans',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
