# Generated by Django 3.2.6 on 2021-08-15 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0018_auto_20210815_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.skills')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='skills',
            field=models.ManyToManyField(through='players.PlayerSkills', to='players.Skills'),
        ),
    ]
