# Generated by Django 3.2.6 on 2021-08-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0020_skills_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerskills',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='playerskills',
            old_name='skill_id',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='category_id',
            new_name='category',
        ),
    ]
