# Generated by Django 3.2.6 on 2021-08-19 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0023_auto_20210819_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='plans',
            options={'verbose_name': 'Plans'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Player'},
        ),
        migrations.AlterModelOptions(
            name='playerskills',
            options={'verbose_name': 'Player_Skills'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Skills'},
        ),
    ]
