# Generated by Django 3.2.6 on 2021-08-19 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0024_auto_20210820_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='comment',
            field=models.CharField(max_length=255, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_name',
            field=models.CharField(max_length=255, verbose_name='skill_name'),
        ),
    ]
