# Generated by Django 3.2.6 on 2021-08-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0025_auto_20210820_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
