# Generated by Django 3.2.6 on 2021-08-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0027_auto_20210821_0946'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerskills',
            unique_together={('player', 'skill')},
        ),
    ]
