# Generated by Django 3.2.6 on 2021-08-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0029_alter_playerskills_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='plan_image'),
        ),
    ]
