# Generated by Django 3.2.6 on 2021-08-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0030_alter_plans_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='image_filed'),
        ),
    ]
