# Generated by Django 3.2.6 on 2021-08-26 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0031_alter_plans_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerskills',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='playerskills',
            name='modified_by',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
