# Generated by Django 3.2.6 on 2021-08-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0032_auto_20210826_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerskills',
            name='modified_at',
            field=models.DateTimeField(default=''),
        ),
    ]
